# Generated by Django 3.1.4 on 2021-01-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorun', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runlog',
            old_name='action',
            new_name='applicationId',
        ),
        migrations.RenameField(
            model_name='runlog',
            old_name='name',
            new_name='featureId',
        ),
        migrations.AddField(
            model_name='runlog',
            name='url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
