# Generated by Django 3.1.4 on 2021-01-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorun', '0002_auto_20210104_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shellPath', models.CharField(max_length=100)),
                ('logPath', models.CharField(max_length=100)),
            ],
        ),
    ]
