# Generated by Django 3.1.4 on 2021-01-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorun', '0003_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='action',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
